### ISSUE TITLE
NeuroElf console

### ISSUE THREAD

**Issue by BrainStormCenter** [neuroelf/neuroelf-matlab#1]
Closing NE while the console is still open causes an error.
NE cannot be restarted nor can the console be closed.
Error message below.

>NeuroElf (17080412): figure...Error using neuroelf_gui (line 579)
Error creating main figure: Couldn't create figure from TFG file
(/Users/jcraggs/Documents/MATLAB/neuroelf-matlab/_core/tfg/neuroelf.tfg): Index
exceeds matrix dimensions...
> 
>Error while evaluating Figure CloseRequestFcn`

**Comment by neuroelf** [comment]
Hey, thanks for the bug report!

Could you please describe the steps to reproduce? And what exactly does "console" refer to?
