### ISSUE TITLE
Convert nii to VTC

### ISSUE THREAD

**Issue by alexsayal** [neuroelf/neuroelf-matlab#2]
Hello,

Is it possible to use Neuroelf to convert from a processed functional .nii file to BrainVoyager's VTC format? I was told this was possible but I can't find this option :/

Thank you in advance,

**Comment by igorkagan** [comment]
One simple way is
`vtc = importvtcfromanalyze(nii); % this is a private function from \@neuroelf\private`
where nii is a cell array with .nii filenames -- if it is only one file, still include it in the brackets: 
`nii = {'path_to_nii_file'};`
Looking into this function might help you to figure out how to do in using only proper NeuroElf-exposed methods.

**Comment by alexsayal** [comment]
Thank you @igorkagan.

I did manage to do this using ```importvtcfromanalyze()```. Example script [here](https://github.com/alexsayal/fmriprep2BV).

**Comment by BrainStormCenter** [comment]
Thank you! I've been wanting to do this for a while but didn’t know how.
