### ISSUE TITLE
Error when launching neuroelf_gui

### ISSUE THREAD

**Issue by hansonliu1** [neuroelf/neuroelf-matlab#5]
Hello,

I installed v1.1, but each time I try to launch NeuroElf by typing in "neuroelf_gui", it opens a second window bu then shows an error. Whenever this happens, I'm also unable to exit MatLab or the second window, and have to close them through Task Manager.

I also tried uninstalling and reinstalling with the flat folder snapshot, as well as v1.0, but I'm having similar errors. Is there a way around this? Thank you very much

![Screenshot (220)](https://user-images.githubusercontent.com/69211252/89445378-11c16100-d721-11ea-831d-958ca9693362.png)

**Comment by igorkagan** [comment]
see https://github.com/neuroelf/neuroelf-matlab/issues/4

**Comment by hansonliu1** [comment]
Hi, it works on MATLAB 2014. Thank you!
In the program, when I go to Tools > SPM preprocessing, I get a pop-up error saying "No supported SPM version available." I have SPM files in my NeuroElf_v11_7251 folder, I'm wondering if there's any ways around this? Thanks in advance

**Comment by neuroelf** [comment]
I assume that I have fixed this (see closed issue 4; thanks Igor for leaving the comment).

As for SPM preprocessing, currently, SPM8 is needed, and it must be on the path.
